docker-build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build -t jgoerzen/nncp .
    - docker tag jgoerzen/nncp jgoerzen/nncp:8.5.0
    - docker push jgoerzen/nncp
    - docker push jgoerzen/nncp:8.5.0
  only:
    - master